### ISSUE TITLE
feat: simpler `copyWith` syntax

### ISSUE THREAD

**Issue by felangel** [felangel/data_class#12]
**Description**

It'd be nice to revert back to the original `copyWith` API (no lambdas) but be able to maintain the ability to copyWith null values.

**Desired API**

```dart
@Data()
class Person {
  final String name;
  final String? nickname;
}

void main() {
  const dash = Person(name: 'Dash', nickname: 'Dashy');
  print(dash.copyWith()); // Person(name: Dash, nickname: Dashy)
  print(dash.copyWith(name: 'Sparky')); // Person(name: Sparky, nickname: Dashy)
  print(dash.copyWith(nickname: null)); // Person(name: Dash, nickname: null)
}
```

**Additional Context**

https://github.com/felangel/data_class/issues/3#issuecomment-2117557442

**Comment by felangel** [comment]
I’ll work on this later today 👍

**Comment by dickermoshe** [comment]
It would awesome if this `copyWith` worked liked freezed where you can do nested `copyWith`s

**Comment by felangel** [comment]
> It would awesome if this `copyWith` worked liked freezed where you can do nested `copyWith`s

I’ll have a look and plan to spend some time on this later today, thanks!

**Comment by pedromassango** [comment]
What is the new copyWith syntax?

**Comment by felangel** [comment]
> What is the new copyWith syntax?

The current syntax uses lambdas to get around not being able to set values to null:

```dart
dash.copyWith(name: () => 'sparky'); // Set name to 'sparky'
dash.copyWith(name: () => null); // Set name to null
dash.copyWith(); // Leave name as is
```

The desired syntax would be:

```dart
dash.copyWith(name: 'sparky'); // Set name to 'sparky'
dash.copyWith(name: null); // Set name to null
dash.copyWith(); // Leave name as is
```

**Comment by pedromassango** [comment]
Is that a limitation of Macros or something?

I could give it a try if you want :)

**Comment by felangel** [comment]
I think we'd need to switch to using a factory constructor and redirect to a private implementation of the class in order to make this work. Not sure if this is possible with macros yet but I'm planning to spend some time on it later today. Feel free to give it a shot if you'd like! All contributions are appreciated 💙

**Comment by Sten435** [comment]
> I think we'd need to switch to using a factory constructor and redirect to a private implementation of the class in order to make this work. Not sure if this is possible with macros yet but I'm planning to spend some time on it later today. Feel free to give it a shot if you'd like! All contributions are appreciated 💙

Is this even possible in dart ?

You should need a literal like _undefined_ to be the default when nothing is passed, but that accepts null.

I don't think that is possible ATM

**Comment by felangel** [comment]
> > I think we'd need to switch to using a factory constructor and redirect to a private implementation of the class in order to make this work. Not sure if this is possible with macros yet but I'm planning to spend some time on it later today. Feel free to give it a shot if you'd like! All contributions are appreciated 💙
> 
> Is this even possible in dart ?
> 
> You should need a literal like _undefined_ to be the default when nothing is passed, but that accepts null.
> 
> I don't think that is possible ATM

It’s possible I have a p.o.c but it requires a subclass and redirecting constructor which I’m not sure is possible to generate with macros currently. I’ll know more in a bit 👍

**Comment by dickermoshe** [comment]
@felangel 
Just curious overall what your goal for this package is.
Remi is working on migrating his package `freezed` to macros, I'm just wonder what your mindset is.

Thanks!

**Comment by felangel** [comment]
> @felangel Just curious overall what your goal for this package is. Remi is working on migrating his package `freezed` to macros, I'm just wonder what your mindset is.
> 
> Thanks!

The goal of this package is to implement data classes as a macro. Iirc freezed includes a lot of additional APIs like unions, custom json serialization, etc. which are outside the scope of a data class imo.

I’m mostly building this because I was excited to try macros and because I would use it in my apps (especially for bloc states) 🙂

Hope that helps! 👍

**Comment by Sten435** [comment]
@felangel is this approach also posible without macros?

**Comment by felangel** [comment]
> @felangel is this approach also posible without macros?

Yup but you'd just need to write the code that the macros generate manually for each class.
