### ISSUE TITLE
refactor: decompose into smaller macros (e.g. `Equatable`, `Copyable`, ...)

### ISSUE THREAD

**Issue by felangel** [felangel/data_class#13]
It would both clean up the code and make it possible to use macros like `@Equatable()`, `@Copyable()` independently of `@Data()`

**Comment by warioddly** [comment]
If we start dividing, then can we also add `fromJson()` and `toJson()` (Jsonable macros) if possible , divide them too? if so, I would like to add such a feature to the library? #5

**Comment by felangel** [comment]
I'm still not convinced that `toJson` and `fromJson` make sense to be part of a data class. Happy to discuss 👍

**Comment by felangel** [comment]
The initial refactor is all done now so closing this 🎉
