### ISSUE TITLE
feat: A macros for generating fake data

### ISSUE THREAD

**Issue by warioddly** [felangel/data_class#18]
**Description**
When developing, sometimes you have to fill models with data with your own hands when there is no other data or use third-party packages

**Desired Solution**
Give the opportunity to add an annotation to generate fake data

**Alternatives Considered**
https://pub.dev/packages/faker

Yes, it sounds so easy, in fact, you have to take a lot into account, like the length of the strings that you want to generate, etc.) But is it possible to do this with anatations on top of class properties?) If this feature is not suitable for this plugin, can we open a new repo as a new plugin?

**Comment by felangel** [comment]
Hi @warioddly 👋 
Thanks for opening an issue!

That seems like it might be out of scope for this library since fake data probably belongs in a mock/fakes package rather than a data_class package. What do you think?

**Comment by warioddly** [comment]
Yes, I also think that it goes beyond the scope of this plugin. But I also think that the data of the class properties also belongs to the data part, or is this a bad idea and we should make another package? I had a question about this👾)

**Comment by warioddly** [comment]
it would be great not to create separate classes for generation fake data, but just attach an annotation to the properties and the class.

**Comment by felangel** [comment]
Yeah I think ideally this should belong in a separate package and you can stack annotations as needed 👍 
Closing this for now but happy to continue the conversation if you have any additional comments/thoughts.
