### ISSUE TITLE
Necessary fields in copyWith()

### ISSUE THREAD

**Issue by warioddly** [felangel/data_class#3]
Will there be support for displaying only the necessary fields in copyWith()

**Comment by felangel** [comment]
Can you elaborate? The current `copyWith` has all optional arguments so you can just call `copyWith()` to create an identical copy or override one or more fields.

**Comment by warioddly** [comment]
I looked at all the documentation about Macro, but did not find (partially found something) information about passing arguments to Macro (classes?)

**Comment by warioddly** [comment]
```dart
[
     '=> ',
     clazzName,
     '(',
          for (final field in fields)
          ...[field.identifier.name,': ', field.identifier.name, ' ?? ', 'this.',field.identifier.name, ','],
     ');'
],
```

I thought it would be cool to customize these parts (other similar parts too) by passing arguments to the Macro

**Comment by warioddly** [comment]
https://github.com/dart-lang/language/blob/main/working/macros/feature-specification.md#type-annotation-arguments

**Comment by felangel** [comment]
@warioddly what kind of customization would you like to see?

**Comment by pedromassango** [comment]
@felangel why did we moved from:
```dart
  final sparky = dash.copyWith(name: 'Sparky');
```

to this
```dart
  final sparky = dash.copyWith(name: () => 'Sparky');
```

At least that is what I'm seeing in the updated Readme. Ideally we keep it similar to what we currently use for a smooth migration

**Comment by tenhobi** [comment]
@pedromassango because this allows you to 

- not pass anything (or pass null) so you dont change the value, using  `name: null`
- change the value, using `name: () => 'Alpha'`
- change the value to null (clear the value), using `name: () => null`

**Comment by josiahsrc** [comment]
> @felangel why did we moved from:
> 
> ```dart
> 
>   final sparky = dash.copyWith(name: 'Sparky');
> 
> ```
> 
> 
> 
> to this
> 
> ```dart
> 
>   final sparky = dash.copyWith(name: () => 'Sparky');
> 
> ```
> 
> 
> 
> At least that is what I'm seeing in the updated Readme. Ideally we keep it similar to what we currently use for a smooth migration

Agreed. Also, `() =>` feels boilerplatey. I wonder if it's possible to use the same implementation that freezed has. Iirc they solved this without lambdas https://pub.dev/packages/freezed

**Comment by felangel** [comment]
> > @felangel why did we moved from:
> > ```dart
> >   final sparky = dash.copyWith(name: 'Sparky');
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to this
> > ```dart
> >   final sparky = dash.copyWith(name: () => 'Sparky');
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > At least that is what I'm seeing in the updated Readme. Ideally we keep it similar to what we currently use for a smooth migration
> 
> Agreed. Also, `() =>` feels boilerplatey. I wonder if it's possible to use the same implementation that freezed has. Iirc they solved this without lambdas https://pub.dev/packages/freezed

Thanks, I’ll have closer look 👍

**Comment by felangel** [comment]
Closing this for now and will track the new `copyWith` syntax in #12
