### ISSUE TITLE
Update data_class package to support the latest macros version

### ISSUE THREAD

**Issue by mg3994** [felangel/data_class#31]
**Description**

Currently, the `data_class` package is not compatible with the latest version of the macros package `(0.1.2-main.0)`. This is causing issues with code generation, as certain APIs have been renamed or removed in the latest macros version.

**Steps to Reproduce:**

1. Attempt to use the data_class package with macros version 0.1.2-main.0.
2. Observe errors related to missing or renamed APIs.

**Desired Solution**

Always be with latest Version

**Additional Context**

* The macros package is currently under development and is considered an experimental feature.
* Further API changes and updates are expected in future versions of the macros package.
* It's recommended to periodically check for updates and changes in the macros package to ensure compatibility with the data_class package. , As most of Users were using the Master Branch of flutter to just check Macros

**Comment by felangel** [comment]
Hi @mg3994 👋 
Thanks for opening an issue!

I just upgraded locally and found no issues. See this [pull request](https://github.com/felangel/data_class/pull/32).

Can you please provide some more context regarding the errors your seeing, the pubspec.lock you have, and the version of the dart sdk you're using? Thanks!

**Comment by felangel** [comment]
Closing for now since it appears the package is compatible with the latest version of `package:macros`. Let me know if there's anything I missed, thanks!
