### ISSUE TITLE
fix: support private fields

### ISSUE THREAD

**Issue by manuel-plavsic** [felangel/data_class#38]
**Description**
Support private fields.

**Steps To Reproduce**

1. Create any private field for a class annotated with `@Data`.
2. Try to run the dart or flutter app, or click on Problems.
3. Notice the error: _Named parameters can't start with an underscore.dart[private_optional_parameter](https://dart.dev/diagnostics/private_optional_parameter)_.

**Expected Behavior**
The generated constructor should take as argument the same field name, but drop the leading underscore. Within the initializer list, the value should be assigned to the internal private field.

I don't think any extra care is needed: in case another field is already defined with this name (i.e. the same as the private field, but without the underscore), then the error _The name `x` is already defined_ should be displayed under Problems.

**Comment by felangel** [comment]
Hi @manuel-plavsic 👋 
Thanks for opening an issue!

Can you elaborate on the use case you have in mind? Typically data classes don't contain private fields in my experience.

**Comment by felangel** [comment]
Closing for now but happy to continue the discussion, thanks!

**Comment by manuel-plavsic** [comment]
I thought they would be useful since sometimes it is better to keep some fields private. How do you handle this scenario? Do you typically introduce an intermediate layer consisting of a DTO class with public fields, which gets mapped to a non-DTO class with private fields?
