### ISSUE TITLE
feat: `copyWith` should support setting nullable fields to `null`

### ISSUE THREAD

**Issue by felangel** [felangel/data_class#4]
Currently it's not possible to create a copy of an object and set fields to `null`.

**Comment by orestesgaolin** [comment]
What would you say about an alternative syntax `copyWith(name: (value: "Dash"));` where passed parameter is a record with named argument defined as `({T? value})`?

**Comment by felangel** [comment]
> What would you say about an alternative syntax `copyWith(name: (value: "Dash"));` where passed parameter is a record with named argument defined as `({T? value})`?

The latest version now supports the original syntax while still allowing you to set fields to `null` 🎉


https://github.com/felangel/data_class/assets/8855632/f9d5000a-6938-42fa-9b31-aad66af187ec

**Comment by orestesgaolin** [comment]
That's so cool! Congrats on figuring this out
